lane :bonjour do

	scan(
		code_coverage: true
	)
	xcov

end

lane :deplot do
	if git_branch() == "master"
		version = get_version_number()
		set_github_release(
			repository_name: "NicoK78/fastlane-demo",
			name: version,
			tag_name: "#{version}",
			description: changelog_from_git_commits(),
			commitish: "master"
		)
	end
end
